config/routes.rb
Rails.application.routes.draw do
  resources :hauptbuches
  root   'static_pages#home'
  
  get 'bookings/new'
  get 'users/new'

  get 'konto/show'
  
  get  '/hauptbuch', to: 'hauptbuch#index'

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :datens
  resources :bookings
  
  resources :users do
    member do
      get :bookings
    end
  end
  
  resources :users do
    member do
      get :hauptbuchs
    end
  end
end

app/models/hauptbuch.rb
class Hauptbuch < ApplicationRecord
  has_many :kontos
  belongs_to :user
end

app/controllers/hauptbuches_controller.rb
class HauptbuchesController < ApplicationController
  before_action :set_hauptbuch, only: [:show, :edit, :update, :destroy]

  # GET /hauptbuches
  # GET /hauptbuches.json
  def index
    @hauptbuches = current_user.hauptbuches.all
  end

  # GET /hauptbuches/1
  # GET /hauptbuches/1.json
  def show
  end

  # GET /hauptbuches/new
  def new
    @hauptbuch = Hauptbuch.new
  end

  # GET /hauptbuches/1/edit
  def edit
  end

  # POST /hauptbuches
  # POST /hauptbuches.json
  def create
    @hauptbuch = Hauptbuch.new(hauptbuch_params)

    respond_to do |format|
      if @hauptbuch.save
        format.html { redirect_to @hauptbuch, notice: 'Hauptbuch was successfully created.' }
        format.json { render :show, status: :created, location: @hauptbuch }
      else
        format.html { render :new }
        format.json { render json: @hauptbuch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hauptbuches/1
  # PATCH/PUT /hauptbuches/1.json
  def update
    respond_to do |format|
      if @hauptbuch.update(hauptbuch_params)
        format.html { redirect_to @hauptbuch, notice: 'Hauptbuch was successfully updated.' }
        format.json { render :show, status: :ok, location: @hauptbuch }
      else
        format.html { render :edit }
        format.json { render json: @hauptbuch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hauptbuches/1
  # DELETE /hauptbuches/1.json
  def destroy
    @hauptbuch.destroy
    respond_to do |format|
      format.html { redirect_to hauptbuches_url, notice: 'Hauptbuch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hauptbuch
      @hauptbuch = Hauptbuch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hauptbuch_params
      params.fetch(:hauptbuch, {})
    end
end

app/helpers/hauptbuches_helper.rb
module HauptbuchesHelper
end

app/views/hauptbuches/_form.html.erb
<%= form_for(hauptbuch) do |f| %>
  <% if hauptbuch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hauptbuch.errors.count, "error") %> prohibited this hauptbuch from being saved:</h2>

      <ul>
      <% hauptbuch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hauptbuches/edit.html.erb
<h1>Editing Hauptbuch</h1>

<%= render 'form', hauptbuch: @hauptbuch %>

<%= link_to 'Show', @hauptbuch %> |
<%= link_to 'Back', hauptbuches_path %>

app/views/hauptbuches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hauptbuches</h1>

<table class="table table-striped">
  <thead>
    <tr>
    
    </tr>
  </thead>

  <tbody>
    <% @hauptbuches.each do |hauptbuch| %>
      <tr>
        <td>
          <%= link_to hauptbuch.konto_name,  konto_show_path(
                                        :konto_name => hauptbuch.konto_name ) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/hauptbuches/new.html.erb
<h1>New Hauptbuch</h1>

<%= render 'form', hauptbuch: @hauptbuch %>

<%= link_to 'Back', hauptbuches_path %>

app/views/hauptbuches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hauptbuch_path(@hauptbuch) %> |
<%= link_to 'Back', hauptbuches_path %>