config/routes.rb
Rails.application.routes.draw do
  resources :hauptbuches
  root   'static_pages#home'
  
  get 'bookings/new'
  get 'users/new'

  get 'konto/show'
  
  get  '/hauptbuch', to: 'hauptbuch#index'

  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  #resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :datens
  resources :bookings
  
  resources :users do
    member do
      get :bookings
    end
  end
  
  resources :users do
    member do
      get :hauptbuchs
    end
  end
end

app/views/layouts/_base.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Get Shit Done Kit by Creative Tim</title>

    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "//google-code-prettify.googlecode.com/svn/loader/run_prettify.js" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Grand+Hotel|Open+Sans:400,300' %>


    <%= yield :style %>
  </head>
  <body data-features="<%= yield :features %>" class="<%= yield :class %>">

    <%= yield %>

  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Impressum",   about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "kibuso.de", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Hilfe", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Hauptbuch", hauptbuches_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Buchungen <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Alle Buchungen", bookings_path %></li>
              <li><%= link_to "Neue Buchung", bookings_new_url %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Konto <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Ausloggen", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Einloggen", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_header_backup.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "kibuso.de", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Hilfe", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Hauptbuch", hauptbuches_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Buchungen <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Alle Buchungen", bookings_path %></li>
              <li><%= link_to "Neue Buchung", bookings_new_url %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Konto <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Einstellungen", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Ausloggen", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Einloggen", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>